profile_user/urls.py
from django.urls import path

app_name = 'profile'

urlpatterns = [

]

tweet/urls.py
from django.urls import path
from .views import home_view, detail_view, list_view, crete_view

app_name = 'tweet'

urlpatterns = [
    path('', home_view, name='home'),
    path('list', list_view, name='list'),
    path('create', crete_view, name='crete'),
    path('details/<int:pk>', detail_view, name='details'),

]

tweetRoot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profile_user.urls')),
    path('', include('tweet.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

profile_user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from tweetRoot.utils.root_utils import customer_image_file_path


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio yet")
    image = models.ImageField(default='default.jpg', upload_to=customer_image_file_path)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{str(self.user)}'s profile "

    class Meta:
        db_table = 'profile'


def user_creation_receiver(sender, instance, created, *args, **kwargs):
    # create Profile for ech user (Singleton)
    if created:
        return Profile.objects.create(user=instance)


post_save.connect(user_creation_receiver, sender=User)

tweet/models.py
import random

from django.db import models
from tweetRoot.utils.root_utils import customer_image_file_path
from PIL import Image


class Tweet(models.Model):
    content = models.TextField(blank=True, null=True)
    image = models.ImageField(default="no_image.jpg", upload_to=customer_image_file_path)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'tweet: {self.pk}'

    class Meta:
        db_table = 'tweet'

    def save(self, *args, **kwargs):
        super(Tweet, self).save(*args, **kwargs)

        try:
            img = Image.open(self.image.path)
            output_size = (300, 300)

            if img.height > 300 or img.width > 300:
                img.thumbnail(output_size)
                img.save(self.image.path)
        except IOError:
            print(f'save problem with file in Tweet model')

    def serializer(self):
        # crete and return object for js
        return {
            "pk": self.pk,
            "content": self.content,
            "like": random.randint(1, 100),
            "img": self.image.url
        }

tweet/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field

from django import forms
from .models import Tweet

MAX_TWEET_LENGTH = 240


# tweet form with field content also change label and placeholder for text field
class CreateTweetForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateTweetForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = "New tweet"

    content = forms.CharField(
        widget=forms.Textarea(attrs={
            "id": "tweet_field",
            "rows": "3",
            "label": "tweets",
            'placeholder': 'Please enter your tweet here , max size 240 chars'
        }),
        error_messages={'required': 'max size 240 chars'},

    )

    # todo crispy forms layout ?
    helper = FormHelper()
    helper.layout = Layout(
        Field('content', css_class='form-control-lg'),
    )

    class Meta:
        model = Tweet
        fields = ("content",)

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) > MAX_TWEET_LENGTH:
            raise forms.ValidationError("this is to big tweet size")

        return content

profile_user/views.py
from django.shortcuts import render

# Create your views here.

tweet/views.py
import random
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.http import is_safe_url
from django.conf import settings
from .models import Tweet
from .forms import CreateTweetForm
from django.contrib import messages
from django.shortcuts import redirect


def home_view(request):
    """
    home view that have list of tweets and form for creating new tweet
    list and form handled by js requests
    """
    form = CreateTweetForm()
    return render(request, 'tweet/home.html', {'form': form})


def crete_view(request, *args, **kwargs):
    """
    creating new tweet thru the ajax and js
    """
    form = CreateTweetForm(request.POST or None)

    # get data from hidden field at tweet creation
    # next redirect to home page
    next_url = request.POST.get('next') or None
    if form.is_valid():
        form.save()

        if request.is_ajax():
            return JsonResponse({"msg": 'created'}, status=201)

        if next_url and is_safe_url(next_url, settings.ALLOWED_HOSTS):
            return redirect(next_url)

    # else
    form = CreateTweetForm()

    context = {
        "form": form
    }
    return render(request, 'tweet/create_tweet.html', context)


def list_view(request, *args, **kwargs):
    """
    get qs of all tweets and return as js list object
    or return error message
    """
    try:
        qs = Tweet.objects.all().order_by('-timestamp')
        list_of_tweets = [x.serializer() for x in qs]
        return JsonResponse({"data": list_of_tweets}, status=200)

    except Tweet.DoesNotExist:
        return JsonResponse({"msg": "not found"}, status=404)


def detail_view(request, pk):
    """
    get tweet by pk
    """
    status = None
    data = {
        "pk": pk,
    }

    try:
        tweet_obj = Tweet.objects.get(pk=pk)
        data['content'] = tweet_obj.content
        data['img'] = tweet_obj.image.url
        status = 200

    except Tweet.DoesNotExist:
        data['msg'] = 'not found'
        status = 404

    finally:
        return JsonResponse(data, status=status)

templates/alerts.html
{% load static %}
<div class="container mt-3">
    {% if messages %}
        {% for element in messages %}
            <div id="alert_box" class="alert alert-{{ element.tags }} alert-dismissible fade show" role="alert">
                {{ element }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <script>
                let elem = document.getElementById("alert_box")
                setTimeout(() => {
                    elem.style.display = "none"
                }, 2000)
            </script>
        {% endfor %}
    {% endif %}
</div>

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    {% comment %} bootstrap 4.6 v {% endcomment %}
    {% comment %}  https://getbootstrap.com/docs/4.6/getting-started/introduction/  {% endcomment %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Tweet</title>

    {% block head %}

    {% endblock %}
</head>
<body>

{% comment %} nav bar {% endcomment %}
<div class="mb-auto">
    {% include 'navbar.html' %}
</div>
{# django mesages #}
<div class="mt-auto">
{% include 'alerts.html' %}
</div>
{% comment %} main content {% endcomment %}
<div class="container-fluid mt-auto">
    {% block main %}{% endblock %}
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

{# additional scripts from other pages #}
{% block scripts %}{% endblock %}
</body>
</html>

templates/navbar.html
{% load static %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'tweet:home' %}">Tweet</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'tweet:crete' %}">Create <span class="sr-only">(current)</span></a>
            </li>

            {% comment %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            {% endcomment %}

        </ul>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>

            {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link " style="color: #f5aeae" href="{% url 'admin:index' %}" tabindex="-1"
                       aria-disabled="true">Admin</a>
                </li>
            {% endif %}
        </ul>

        {% comment %}
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% endcomment %}

    </div>
</nav>

templates/tweet/create_tweet.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block main %}
    <div style="width: 40vw; height: auto; margin-left: 3vw">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">submit</button>
        </form>
    </div>

{% endblock %}

templates/tweet/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block main %}

    <br>
    <h3 class="text-center mt-4"> Tweets </h3>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col col-lg-2">
            </div>
            <div class="col-md-6">
                <div id="tweetList">
                    <p>Loading .. </p>
                </div>
            </div>

            <div class="col col-lg-4">
                <div id="alert_box"></div>

                <form action="{% url 'tweet:crete' %}" class="bootstrap4" method="POST" id="tweet_create_form">
                    {% comment %}
                        transfer user with js after submitting
                        form to home with next value
                    {% endcomment %}
                    <input type="hidden" value="{% url 'tweet:home' %}" name="next"/>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">submit</button>
                </form>
            </div>
        </div>
    </div>target



{% endblock %}

{% block scripts %}
    <script src="{% static "js/tweets.js" %}"></script>
{% endblock %}